#!/bin/bash
# This file is @generated by <https://github.com/liblaf/copier-python>.
# DO NOT EDIT!
set -o errexit
set -o nounset
set -o pipefail

if [[ -f "pixi.lock" ]]; then
  pixi install
fi

if [[ -f "uv.lock" ]]; then
  uv sync --all-extras --all-groups
fi
