#!/bin/bash
# This file is @generated by <https://github.com/liblaf/copier-python>.
# DO NOT EDIT!

if [[ -n ${__USAGE-} ]]; then
  # skip when in shell completions
  return
fi

DEBOUNCE_FILE="${DEBOUNCE_FILE:-"/tmp/debounce"}"
DEBOUNCE_INTERVAL="${DEBOUNCE_INTERVAL:-"1"}"
if [[ -f ${DEBOUNCE_FILE} ]]; then
  last_exec_time="$(< "${DEBOUNCE_FILE}")"
  current_time="$(date +%s)"
  if ((current_time - last_exec_time < DEBOUNCE_INTERVAL)); then
    return
  fi
fi
date "+%s" > "${DEBOUNCE_FILE}"

if [[ -f "pixi.lock" ]]; then
  args=()
  if [[ -t 2 ]]; then args+=(--color=always); fi
  eval "$(pixi shell-hook "${args[@]}")"
fi

if [[ -f "uv.lock" ]]; then
  uv sync --all-extras --all-groups
  # shellcheck disable=SC2016
  sd '^(\s*)?(?P<key>include-system-site-packages)(\s*)?=(\s*)?(?<val>.*)$' '$key = true' ".venv/pyvenv.cfg"
  # shellcheck disable=SC1091
  source ".venv/bin/activate"
fi
