name: Export

on:
  push:
  workflow_dispatch:

jobs:
  export:
    name: Export
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: |-
            requirements-dev.lock
            requirements.lock
      - name: Install Dependencies
        run: pip install --requirement requirements-dev.lock --requirement requirements.lock
      - name: Export Template Mesh
        run: |-
          mkdir --parents --verbose template/
          python tools/export.py
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: template
          path: template/

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - export
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: template
          path: template/
      - name: Create GitHub Release
        uses: liblaf/repo/.github/actions/release@main
        with:
          tag: template
          files: template/*
          recreate: true
